FROM golang:1.21-alpine
WORKDIR /app
RUN apk add --no-cache git
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go install github.com/cosmtrek/air@latest
EXPOSE 3004
CMD ["air", "-c", ".air.toml"]