groups:
  - name: live_service_alerts
    rules:
      - alert: HighErrorRate
        expr: rate(live_service_http_errors_total[5m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "High error rate in live service"
          description: "Error rate is {{ $value }} per second"

      - alert: HighLatency
        expr: histogram_quantile(0.95, rate(live_service_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High latency in live service"
          description: "95th percentile latency is {{ $value }} seconds"

      - alert: ServiceDown
        expr: up{job="live-service"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Live service is down"
          description: "Service has been down for more than 1 minute"

      - alert: HighMemoryUsage
        expr: process_resident_memory_bytes{job="live-service"} / process_virtual_memory_bytes{job="live-service"} > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High memory usage in live service"
          description: "Memory usage is at {{ $value | humanizePercentage }}"

      - alert: WebSocketConnectionsHigh
        expr: live_service_websocket_connections > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High WebSocket connections"
          description: "{{ $value }} active WebSocket connections"

      - alert: DatabaseConnectionsHigh
        expr: live_service_db_connections > 50
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High database connections"
          description: "{{ $value }} active database connections"

      - alert: RedisMemoryHigh
        expr: redis_memory_used_bytes / redis_memory_max_bytes > 0.8
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "High Redis memory usage"
          description: "Redis memory usage is at {{ $value | humanizePercentage }}"

      - alert: SessionRecordingFailed
        expr: rate(live_service_recording_failures_total[15m]) > 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Session recording failures"
          description: "{{ $value }} recording failures in the last 15 minutes"

      - alert: PaymentProcessingFailed
        expr: rate(live_service_payment_failures_total[15m]) > 0.1
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Payment processing failures"
          description: "Payment failure rate is {{ $value }} per second"